[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.1.2",
    "django>=6.1",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.3.0",
    "django-cors-headers>=4.3.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.12",
    "uvicorn>=0.52.4",
    "whitenoise>=6.12.0",
]

[dependency-groups]
dev = [
  "mypy>=1.13",
  "django-stubs>=6.1.0",
  "djangorestframework-stubs>=3.18.0",
  "pytest>=9.1.1",
  "pytest-django>=4.14.0",
  "pytest-dotenv>=0.5.2",
  "ruff>=0.16.4",
]

[tool.ruff]
line-length = 79
target-version = "py314"
fix = true
show-fixes = true
indent-width = 4
exclude = [".venv"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "T201",
  "COM812",
  "INP001",
  "D",
  "ANN401",
  "ERA001",
  "A004",
  "CPY001",
  "DJ001",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "PLR2004",
    "S101",
    "S105",
    "S106",
    "SLF001",
]
"*/migrations/*.py" = ["ALL"]
"core/settings.py" = [
    "E501", # Ignore line-length violations for long secret keys or database URLs
]
"**/views.py" = ["ARG002"]
"__init__.py" = ["F401"]


[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
known-first-party = ["core"]

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.14"
include = ["."]
exclude = [
  "**/venv",
  "**/.venv",
  "**/env",
  "**/.env",
  "**/node_modules",
  "**/__pycache__",
  "**/migrations",
]
venv = ".venv"
venvPath = "."
reportIncompatibleVariableOverride = "none"

[tool.mypy]
python_version = "3.14"
plugins = ["mypy_django_plugin.main"]
exclude = ["migrations/"]
ignore_missing_imports = true
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "core.settings"

[tool.pytest.ini_options]
addopts = "-s --color=yes --tb=short"
DJANGO_SETTINGS_MODULE = "core.settings"
testpaths = ["tests"]
env_files = ".env"
filterwarnings = [
  "ignore:No directory at.*staticfiles:UserWarning",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
